services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./resource/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: host

  redis:
    build: ./resource/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./resource/redis/data:/data

  hoverfly:
    image: spectolabs/hoverfly:latest
    container_name: hoverfly
    ports:
      - "8500:8500"  # Proxy port
      - "8888:8888"  # Admin API port
    environment:
      - HOVERFLY_ADMIN_PORT=8888
      - HOVERFLY_PROXY_PORT=8500
    command: ["-webserver"]
