services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./resource/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    network_mode: host

  redis:
    build: ./resource/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./resource/redis/data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=cloudformation,logs,iam,apigateway,lambda,dynamodb,events
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./resource/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4566:4566"

  hoverfly:
    image: spectolabs/hoverfly:latest
    container_name: hoverfly
    ports:
      - "8500:8500"  # Proxy port
      - "8888:8888"  # Admin API port
    environment:
      - HOVERFLY_ADMIN_PORT=8888
      - HOVERFLY_PROXY_PORT=8500
    command: ["-webserver"]
